# Generated by Django 6.0 on 2026-04-09 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True)),
                ('upper_threshold', models.FloatField(default=2.0, help_text='Temperature anomaly above this value triggers alert (°C)')),
                ('lower_threshold', models.FloatField(default=-2.0, help_text='Temperature anomaly below this value triggers alert (°C)')),
                ('rapid_change_threshold', models.FloatField(default=0.5, help_text='Year-over-year change that triggers alert (°C)')),
                ('enabled', models.BooleanField(default=True)),
                ('notification_methods', models.JSONField(default=list, help_text="['email', 'dashboard', 'webhook']")),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('temperature_value', models.FloatField()),
                ('threshold_value', models.FloatField()),
                ('alert_type', models.CharField(choices=[('above_threshold', 'Temperature Above Threshold'), ('below_threshold', 'Temperature Below Threshold'), ('rapid_change', 'Rapid Temperature Change'), ('record_high', 'Record High Temperature'), ('record_low', 'Record Low Temperature')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='dashboard.temperaturealert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-alert__created_at'],
            },
        ),
    ]
